"use client";
import React from "react";
import Layout from "../../components/merchant_components/Layout";
import Header from "@/app/components/merchant_components/Header";
import EmptyOrders from "../orders/EmptyOrders";
import OrderList from "../orders/OrderList";

function Orders() {
  const HeaderData = {
    title: "Orders",
    text: "See who ordered your products",
  };
  const orders = [
    {
      id: 1,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "Paid",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 2,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "delivered",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 3,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "pending",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 4,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A.",
      invoice_no: "202378690",
      current_order_status: "Paid",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "london",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 5,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A.",
      invoice_no: "202378690",
      current_order_status: "delivered",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "New york",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 6,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "pending",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 7,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "pending",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 8,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "Paid",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 9,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "pending",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 10,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "delivered",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
    {
      id: 11,
      text: "2022-05-17T03:24:00",
      order_price: "$435.50",
      date: "27 Nov 2023",
      billing_name: "Shirley A. Lape",
      invoice_no: "202378690",
      current_order_status: "pending",
      email: "Johndoe@yahoo.com",
      country: "Nigeria",
      product_qty: 5,
      state: "Rivers",
      city: "Port Harcourt",
      Address: "123 Peace Street",
      customInformation: "Along The Road",
      order_date: "2022-05-17T03:24:00",
      customer_id: "23143",
      productsOrdered: [
        {
          title: "Perfume",
          productInvoice: "202378690",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "iPhone 15 plus",
          productInvoice: "202378691",
          product_price: "20,000",
          product_status: "In Stock",
        },
        {
          title: "HP Laptop",
          productInvoice: "202378692",
          product_price: "20,000",
          product_status: "In Stock",
        },
      ],
    },
  ];

  // const orders = []

  return (
    <Layout>
      <Header {...HeaderData} />
      {orders.length < 1 ? <EmptyOrders /> : <OrderList />}
    </Layout>
  );
}

export default Orders;
